id: DC4F84ECD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:54:33+00:00'
last_modified: '2022-05-29T08:05:01.712373+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '0373':
      image_group_id: I1PD95916
      title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1683
      order: 71
      base_file: 0373.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
