id: P1D45EBDD
initial_creation_type: ocr
source_metadata:
  volumes:
    9a9ab7259c1a4e9f82dc8d5c55f095e8:
      base_file: v071.txt
      image_group_id: I1PD95916
      title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1683
      volume_number: 71
